<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class M_event_gathering extends CI_Model {

    public function __construct()
    {
        parent::__construct();
    }

    // ------------------HARUS DIPAKAI DI SEMUA MODEL UNTUK HALAMAN DEPAN
    public function MenuGetAbout()
    {
        $this->db->where('id_about', 1);
        return $this->db->get('tb_about')->row();
    }

    public function MenuGetIdolG()
    {
        $this->db->where('del_idol_group', 0);
        return $this->db->get('tb_idol_group')->result();
    }

    public function jumlahkeranjang($idakun)
    {
        $this->db->where('id_akun', $idakun);
        return $this->db->get('tb_metamemesan');
    }
    // ---------------------------CLose HARUS--------------

    public function GetE()
    {
        $this->db->order_by('tgl_event', 'desc');
        $this->db->where('jenis_event', 'event');
        $this->db->where('del_event', 0);
        $this->db->limit(10);
        return $this->db->get('tb_event')->result();
    }

    public function GetG()
    {
        $this->db->order_by('tgl_event', 'desc');
        $this->db->where('jenis_event', 'gathering');
        $this->db->where('del_event', 0);
        $this->db->limit(10);
        return $this->db->get('tb_event')->result();
    }

    public function GetEvent($id_event)
    {
        $this->db->where('del_event', 0);
        $this->db->where('id_event', $id_event);
        return $this->db->get('tb_event')->row();
    }

    public function GetTiket($id_event)
    {
        $this->db->where('del_tiket', 0);
        $this->db->where('id_event', $id_event);
        $this->db->order_by('harga_tiket', 'desc');
        return $this->db->get('tb_tiket');
    }

    public function GetTiket1($id_tiket)
    {
        $this->db->where('del_tiket', 0);
        $this->db->where('id_tiket', $id_tiket);
        return $this->db->get('tb_tiket');
    }

    public function tambahmeta($data)
    {
        $this->db->insert('tb_metamemesan', $data);
    }

    public function getkeranjang($id_akun)
    {
        $this->db->join('tb_tiket C', 'C.id_tiket = A.id_tiket');
        $this->db->join('tb_event B', 'B.id_event = C.id_event');
        $this->db->where('A.id_akun', $id_akun);
        return $this->db->get('tb_metamemesan A');
    }

    public function hapusmeta($id_metamemesan, $id)
    {
        $this->db->where('id_metamemesan', $id_metamemesan);
        $this->db->where('id_akun', $id);
        $this->db->delete('tb_metamemesan');
    }

    public function pesan($id, $no_memesan)
    {
        $email = $this->db->query("SELECT email_akun FROM `tb_akun` WHERE id_akun = '$id'");
        require APPPATH.'libraries/PHPMailer/PHPMailerAutoload.php';

        $sendTo = $email->row('email_akun');
        $message = "<h1>Cara Pembayaran Tiket Online 48FansPontianak</b></h1>
            <legend></legend><br>
            <h2>No. Pembelian = ".$no_memesan."</h2><br>
            <p>Kirim uang ke nomor rekening kami</p>
            <p><b>BCA 123-1371897</b></p>
            <p>Total Pembayaran sesuaikan dengan Harga Total di menu konfirmasi pembayaran,</p>
            <p>Kirim foto resi pembayaran bank ke website di menu konfirmasi pembayaran,</p>
            <p>Kode Tiket dapat diambil di menu Konfirmasi Pembayaran, lalu tekan tombol 'Minta Kode Tiket'</p>
            <p>Untuk mendapatkan Tiket,</p>
            <p>Terima Kasih :)</p>
            <p>Atau Klik link berikut ".base_url()."adm_memesan</p>";
        $subject = "Cara Pembayaran 48FansPontianak";
        $this->SendEmail($data, $sendTo, $message, $subject);

        $this->db->query("INSERT INTO tb_memesan (no_memesan,id_tiket,total_harga,jumlah_tiket,id_akun,status_bayar,tgl_memesan,del_memesan) SELECT '$no_memesan',id_tiket,total_harga,jumlah_tiket,id_akun,status_bayar,tgl_memesan,0 FROM tb_metamemesan where id_akun = $id");
        $this->db->query("DELETE FROM tb_metamemesan WHERE id_akun = $id");
    }

    function SendEmail($data, $sendTo, $message, $subject)
    {
        $hello = '<h1 style="color:#333;font-family:Helvetica,Arial,sans-serif;font-weight:300;padding:0;margin:10px 0 25px;text-align:center;line-height:1;word-break:normal;font-size:38px;letter-spacing:-1px">Cara Pembayaran Tiket Online 48FansPontianak</h1>';
        $thanks = "<br><br><i>This is autogenerated email please do not reply.</i><br/><br/>Thanks,<br/>Admin<br/><br/>";

        $mail = new PHPMailer;
        $mail->isSMTP(true); // telling the class to use SMTP
        $mail->SMTPOptions = array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                ));
        $mail->Host = 'smtp.gmail.com';
        $mail->Port = 587;
        $mail->SMTPSecure = 'tls';
        $mail->SMTPAuth = true;
        $mail->Username = '48fansptk@gmail.com';                 // SMTP username
        $mail->Password = 'pontianak484848';                           // SMTP password

        $mail->setFrom('48fansptk@gmail.com', '48FansPontianak');
        $mail->addAddress($sendTo);     // Add a recipient
        $mail->isHTML(true);                                  // Set email format to HTML
        $mail->WordWrap = 0;
        $mail->Subject = $subject;
        $body = $hello.$message.$thanks;
        $mail->Body = $body;
        $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

        if(!$mail->send()) {
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        } else {
            echo 'Message has been sent';
        }
    }

}

/* End of file M_event_gathering.php */
/* Location: ./application/modules/event_gathering/models/M_event_gathering.php */